#do primeiro artigo do medium

name: Docker

on:
  push:
    branches: [ master ]

jobs:
    deploy:
      
        name: Setup Gcloud Account
        runs-on: ubuntu-latest
        environment: project-secrets
        env:
          IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_APP_NAME }}
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          BASIC_AUTH_USERNAME: ${{ secrets.BASIC_AUTH_USERNAME }}
          BASIC_AUTH_PASSWORD: ${{ secrets.BASIC_AUTH_PASSWORD }}
     
        steps:

        - if: ${{ env.GCP_PROJECT_ID != '' }}
          run: echo 'This step will only run if the secret has a value set.'
        
        - if: ${{ env.BASIC_AUTH_USERNAME == '' }}
          run: echo 'This step will only run if the secret does not have a value set.'
        
        - name: Login
          uses: google-github-actions/setup-gcloud@v0
          with:
            project_id: ${{ secrets.GCP_PROJECT_ID }}
            service_account_email: ${{ secrets.GCP_EMAIL }}
            service_account_key: ${{ secrets.GCP_CREDENTIALS }}
        
        - name: super echo
          run: echo "The selected color is ${{ secrets.GCP_PROJECT_ID }}"
            
        - name: Configure Docker
          run: gcloud auth configure-docker --quiet
            
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Build Docker image
          run: docker build -t $IMAGE_NAME --build-arg BASIC_AUTH_USERNAME_ARG=${{ secrets.BASIC_AUTH_USERNAME }} --build-arg BASIC_AUTH_PASSWORD_ARG=${{ secrets.BASIC_AUTH_PASSWORD }} .

        - name: Push Docker image
          run: docker push $IMAGE_NAME:${{  github.sha }}

        - name: Deploy Docker image
          run: |-
            gcloud run deploy ${{ env.SERVICE }} \
              --region ${{ env.REGION }} \
              --image gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{  github.sha }} \
              --platform "managed" \
              --port 5000