name: Docker Deploy

on:
  push:
    branches: [ master ]

jobs:

    deploy:
      
        name: Deploy
        runs-on: ubuntu-latest
        env:
          PROJECT_ID: mlops-alura-346601
          SERVICE: mov-recsys
          REGION: us-central1
          GCP_EMAIL: gitserviceaccount@mlops-alura-346601.iam.gserviceaccount.com
          IMAGE_NAME: gcr.io/mlops-alura-346601/mov-recsys  #modified***
          BASIC_AUTH_USERNAME: "teste"
          BASIC_AUTH_PASSWORD: "1234"

        steps:
        
        - name: Login
          uses: google-github-actions/setup-gcloud@v0
          with:
            project_id: $PROJECT_ID
            service_account_email: $GCP_EMAIL
            service_account_key: ${{ secrets.GCP_CREDENTIALS }}
            
        - name: Configure Docker
          run: gcloud auth configure-docker --quiet
            
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Build Docker image
          run: docker build -t $IMAGE_NAME --build-arg BASIC_AUTH_USERNAME_ARG=${{ secrets.BASIC_AUTH_USERNAME }} --build-arg BASIC_AUTH_PASSWORD_ARG=${{ secrets.BASIC_AUTH_PASSWORD }} .

        - name: Test Docker image
          run: docker run $IMAGE_NAME sh -c "go test -v" 

        - name: Push Docker image
          run: docker push $IMAGE_NAME

        - name: Deploy Docker image
          run: gcloud run deploy $PROJECT_ID --image $IMAGE_NAME --region us-central1 --platform managed